/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MediVaultAnchorInterface extends Interface {
  getFunction(
    nameOrSignature: "anchorRecord" | "getRecordAnchor"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RecordAnchored"): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorRecord",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordAnchor",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "anchorRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordAnchor",
    data: BytesLike
  ): Result;
}

export namespace RecordAnchoredEvent {
  export type InputTuple = [
    recordReference: string,
    recordHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    recordReference: string,
    recordHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    recordReference: string;
    recordHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MediVaultAnchor extends BaseContract {
  connect(runner?: ContractRunner | null): MediVaultAnchor;
  waitForDeployment(): Promise<this>;

  interface: MediVaultAnchorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorRecord: TypedContractMethod<
    [recordReference: string, recordHash: string],
    [void],
    "nonpayable"
  >;

  getRecordAnchor: TypedContractMethod<
    [recordReference: string],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorRecord"
  ): TypedContractMethod<
    [recordReference: string, recordHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecordAnchor"
  ): TypedContractMethod<[recordReference: string], [string], "view">;

  getEvent(
    key: "RecordAnchored"
  ): TypedContractEvent<
    RecordAnchoredEvent.InputTuple,
    RecordAnchoredEvent.OutputTuple,
    RecordAnchoredEvent.OutputObject
  >;

  filters: {
    "RecordAnchored(string,string,uint256)": TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;
    RecordAnchored: TypedContractEvent<
      RecordAnchoredEvent.InputTuple,
      RecordAnchoredEvent.OutputTuple,
      RecordAnchoredEvent.OutputObject
    >;
  };
}
